/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.etiquetas;

import static com.mycompany.etiquetas.ConexionEpsonCarnes.conectar;
import static com.mycompany.etiquetas.Epson.getPrinterEpson;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.Timer;

/**
 *
 * @author JEOS
 */
public class TurnosCarnes extends javax.swing.JFrame {
    private long lastPrintTime = 0;
    Epson epson;
    
    public TurnosCarnes() {
        this.setUndecorated(true); // sin bordes
        initComponents();
        java.awt.GraphicsDevice gd = 
            java.awt.GraphicsEnvironment.getLocalGraphicsEnvironment().getDefaultScreenDevice();
        gd.setFullScreenWindow(this);
        lblTurno.setText(""+ConexionEpsonCarnes.getAtento());
        epson.getPrinterEpson();
        // Crear un Timer que se repite cada 3000 ms (3 segundos)
        Timer timer = new Timer(3000, e -> {
            // Actualizar el label con el valor más reciente
            lblTurno.setText("" + ConexionEpsonCarnes.getAtento());
            // Actualizar los siguientes turnos
            actualizarSiguientes("SucursalX", next1, next2, next3, next4, next5, next6);
        });
        timer.start(); // Iniciar el timer

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblTurno = new javax.swing.JLabel();
        lblActual = new javax.swing.JLabel();
        btnTurno = new javax.swing.JButton();
        next1 = new javax.swing.JLabel();
        next2 = new javax.swing.JLabel();
        next3 = new javax.swing.JLabel();
        next4 = new javax.swing.JLabel();
        next5 = new javax.swing.JLabel();
        next6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(null);
        getContentPane().setLayout(null);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logot.png"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 30, 370, 130);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bg1.jpg"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 1430, 1090, 420);

        lblTurno.setFont(new java.awt.Font("Segoe UI", 1, 450)); // NOI18N
        lblTurno.setForeground(new java.awt.Color(255, 255, 255));
        lblTurno.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTurno.setText("0");
        getContentPane().add(lblTurno);
        lblTurno.setBounds(0, 190, 1090, 540);

        lblActual.setFont(new java.awt.Font("Segoe UI", 1, 70)); // NOI18N
        lblActual.setForeground(new java.awt.Color(255, 255, 255));
        lblActual.setText("SIGUIENTES :");
        getContentPane().add(lblActual);
        lblActual.setBounds(20, 830, 490, 70);

        btnTurno.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        btnTurno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/turno.png"))); // NOI18N
        btnTurno.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, new java.awt.Color(51, 255, 255), new java.awt.Color(204, 255, 255), new java.awt.Color(0, 51, 51), new java.awt.Color(0, 153, 153)));
        btnTurno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTurnoActionPerformed(evt);
            }
        });
        getContentPane().add(btnTurno);
        btnTurno.setBounds(870, 910, 200, 360);

        next1.setFont(new java.awt.Font("Segoe UI", 1, 68)); // NOI18N
        next1.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(next1);
        next1.setBounds(540, 830, 140, 70);

        next2.setFont(new java.awt.Font("Segoe UI", 1, 68)); // NOI18N
        next2.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(next2);
        next2.setBounds(540, 930, 140, 70);

        next3.setFont(new java.awt.Font("Segoe UI", 1, 68)); // NOI18N
        next3.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(next3);
        next3.setBounds(540, 1030, 160, 70);

        next4.setFont(new java.awt.Font("Segoe UI", 1, 68)); // NOI18N
        next4.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(next4);
        next4.setBounds(540, 1140, 190, 70);

        next5.setFont(new java.awt.Font("Segoe UI", 1, 68)); // NOI18N
        next5.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(next5);
        next5.setBounds(540, 1250, 210, 70);

        next6.setFont(new java.awt.Font("Segoe UI", 1, 68)); // NOI18N
        next6.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(next6);
        next6.setBounds(540, 1350, 200, 70);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/backaz.png"))); // NOI18N
        jLabel1.setToolTipText("");
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1090, 1990);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTurnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTurnoActionPerformed
        long now = System.currentTimeMillis();
        if (now - lastPrintTime >= 3000) { // 3000 ms = 3 segundos
            epson.testPrinterEpsonCarnes();
            lastPrintTime = now;
        } else {
            System.out.println("Esperando cooldown de impresión...");
        }

    }//GEN-LAST:event_btnTurnoActionPerformed

    public static void actualizarSiguientes(String sucursal,
                                            JLabel... labels) {
        // Primero limpiar todos los labels
        for (JLabel lbl : labels) {
            lbl.setText(""); 
        }

        String query = "SELECT numero FROM turnocarnes " +
                       "WHERE DATE(fecha_registro) = CURDATE() AND estatus = 1 " +
                       "ORDER BY numero ASC LIMIT 6";

        try (Connection conn = conectar();
             Statement stmt = conn.createStatement();
             ResultSet rs = stmt.executeQuery(query)) {

            int i = 0;
            while (rs.next() && i < labels.length) {
                labels[i].setText(rs.getString("numero"));
                i++;
            }
            stmt.close();
        } catch (SQLException e) {
            System.out.println("Error al cargar los turnos: " + e.getMessage());
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TurnosCarnes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TurnosCarnes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TurnosCarnes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TurnosCarnes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            TurnosCarnes ventana = new TurnosCarnes();
            ventana.setVisible(true);
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnTurno;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblActual;
    private javax.swing.JLabel lblTurno;
    private javax.swing.JLabel next1;
    private javax.swing.JLabel next2;
    private javax.swing.JLabel next3;
    private javax.swing.JLabel next4;
    private javax.swing.JLabel next5;
    private javax.swing.JLabel next6;
    // End of variables declaration//GEN-END:variables
}
